name: CI

on: pull_request

jobs:
  check:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: setup deps
        run: |
          rustup component add llvm-tools-preview
          # cargo install grcov
          sudo apt -y install llvm

      - name: run
        run: make -C integration-test coverage-percentage-gh

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: coverage bot

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **coverage bot**
            commit ${{ github.sha }} is at `${{ env.COVERAGE_STAT }}`

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            commit ${{ github.sha }} is at `${{ env.COVERAGE_STAT }}`
